/*
 * Tiketeo API
 *
 * Autenticación: Bearer <secret_key> 
 *
 * The version of the OpenAPI document: v1
 * Contact: romario.lopez@tiketeo.mx
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Topup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TopupTests
    {
        // TODO uncomment below to declare an instance variable for Topup
        //private Topup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Topup
            //instance = new Topup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Topup
        /// </summary>
        [Test]
        public void TopupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Topup
            //Assert.IsInstanceOf(typeof(Topup), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ExternalId'
        /// </summary>
        [Test]
        public void ExternalIdTest()
        {
            // TODO unit test for the property 'ExternalId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'FailureReason'
        /// </summary>
        [Test]
        public void FailureReasonTest()
        {
            // TODO unit test for the property 'FailureReason'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'TopupBillerId'
        /// </summary>
        [Test]
        public void TopupBillerIdTest()
        {
            // TODO unit test for the property 'TopupBillerId'
        }
        /// <summary>
        /// Test the property 'BranchId'
        /// </summary>
        [Test]
        public void BranchIdTest()
        {
            // TODO unit test for the property 'BranchId'
        }
        /// <summary>
        /// Test the property 'PosId'
        /// </summary>
        [Test]
        public void PosIdTest()
        {
            // TODO unit test for the property 'PosId'
        }
        /// <summary>
        /// Test the property 'AuthorizationNumber'
        /// </summary>
        [Test]
        public void AuthorizationNumberTest()
        {
            // TODO unit test for the property 'AuthorizationNumber'
        }
        /// <summary>
        /// Test the property 'TicketText'
        /// </summary>
        [Test]
        public void TicketTextTest()
        {
            // TODO unit test for the property 'TicketText'
        }

    }

}
