/*
 * Tiketeo API
 *
 * Autenticación: Bearer <secret_key> 
 *
 * The version of the OpenAPI document: v1
 * Contact: romario.lopez@tiketeo.mx
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Winner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WinnerTests
    {
        // TODO uncomment below to declare an instance variable for Winner
        //private Winner instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Winner
            //instance = new Winner();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Winner
        /// </summary>
        [Test]
        public void WinnerInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOf" Winner
            //Assert.IsInstanceOf(typeof(Winner), instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Claimed'
        /// </summary>
        [Test]
        public void ClaimedTest()
        {
            // TODO unit test for the property 'Claimed'
        }
        /// <summary>
        /// Test the property 'Ticket'
        /// </summary>
        [Test]
        public void TicketTest()
        {
            // TODO unit test for the property 'Ticket'
        }
        /// <summary>
        /// Test the property 'Prize'
        /// </summary>
        [Test]
        public void PrizeTest()
        {
            // TODO unit test for the property 'Prize'
        }

    }

}
